# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6756ea5aabd1c10d290358739f752a2ffa5d7e6c7ab89d2d5418c305ba102d04eddd883392dea21a1732948ae49da4046b29df867048c72b98b7f16839f01b09

test:
  secret_key_base: 6e0824c6afd5bfd944ee1189ea47a6fd4bd9ea01dafdc4a85f53aceae779553397fa7a2dc5042ccc0a5ea06abd0866e6f21b5e62956d9a2dc91a11da63464485

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
